In [151]:
import pickle
import numpy as np
import os 
import pandas as pd


from functions.test_algorithms import *
from functions.random_search import * 
from slim_gsgp_lib.datasets.data_loader import *
import pickle
datasets = [globals()[i] for i in globals() if 'load' in i][2:]

In [103]:
datasets = []
for filename in os.listdir('results/SLIM'):
    if 'struct' in filename:
        datasets.append(filename.split('_struct')[0])

In [147]:
os.listdir('best_params')

['best_gp_istanbul_100_100_False.pkl',
 'best_gp_istanbul_100_100_True.pkl',
 'best_gp_resid_build_sale_price_100_100_False.pkl',
 'best_gp_resid_build_sale_price_100_100_True.pkl',
 'best_gsgp_airfoil_100_100_False.pkl',
 'best_gsgp_airfoil_100_100_True.pkl',
 'best_gsgp_bike_sharing_100_100_False.pkl',
 'best_gsgp_bike_sharing_100_100_True.pkl',
 'best_gsgp_bioav_100_100_False.pkl',
 'best_gsgp_bioav_100_100_True.pkl',
 'best_gsgp_boston_100_100_False.pkl',
 'best_gsgp_boston_100_100_True.pkl',
 'best_gsgp_breast_cancer_100_100_False.pkl',
 'best_gsgp_breast_cancer_100_100_True.pkl',
 'best_gsgp_concrete_slump_100_100_False.pkl',
 'best_gsgp_concrete_slump_100_100_True.pkl',
 'best_gsgp_concrete_strength_100_100_False.pkl',
 'best_gsgp_concrete_strength_100_100_True.pkl',
 'best_gsgp_diabetes_100_100_False.pkl',
 'best_gsgp_diabetes_100_100_True.pkl',
 'best_gsgp_efficiency_cooling_100_100_False.pkl',
 'best_gsgp_efficiency_cooling_100_100_True.pkl',
 'best_gsgp_efficiency_heating_10

In [148]:
with open('best_params/best_slim_airfoil_100_100_True.pkl', 'rb') as f:
    best_params = pickle.load(f)

best_params

{'SLIM+SIG2': {'p_inflate': 0.6,
  'max_depth': 18,
  'init_depth': 9,
  'prob_const': 0.2,
  'prob_replace': 0,
  'p_prune': 0,
  'p_xo': 0,
  'p_struct_xo': 0},
 'SLIM*SIG2': {'p_inflate': 0.6,
  'max_depth': 24,
  'init_depth': 5,
  'prob_const': 0.1,
  'prob_replace': 0,
  'p_prune': 0,
  'p_xo': 0,
  'p_struct_xo': 0},
 'SLIM+ABS': {'p_inflate': 0.4,
  'max_depth': 23,
  'init_depth': 6,
  'prob_const': 0.15,
  'prob_replace': 0,
  'p_prune': 0,
  'p_xo': 0,
  'p_struct_xo': 0},
 'SLIM*ABS': {'p_inflate': 0.9,
  'max_depth': 18,
  'init_depth': 5,
  'prob_const': 0.05,
  'prob_replace': 0,
  'p_prune': 0,
  'p_xo': 0,
  'p_struct_xo': 0},
 'SLIM+SIG1': {'p_inflate': 0.5,
  'max_depth': 18,
  'init_depth': 10,
  'prob_const': 0.15,
  'prob_replace': 0,
  'p_prune': 0,
  'p_xo': 0,
  'p_struct_xo': 0},
 'SLIM*SIG1': {'p_inflate': 0.9,
  'max_depth': 23,
  'init_depth': 6,
  'prob_const': 0.2,
  'prob_replace': 0,
  'p_prune': 0,
  'p_xo': 0,
  'p_struct_xo': 0}}

In [150]:
with open('best_params/best_slim_bike_sharing_100_100_True_struct.pkl', 'rb') as f:
    best_params = pickle.load(f)

best_params

{'SLIM+SIG2': {'p_inflate': 0.6,
  'max_depth': 15,
  'init_depth': 5,
  'prob_const': 0.2,
  'prob_replace': 0.01,
  'p_prune': 0.7,
  'p_xo': 0.8,
  'p_struct_xo': 0.7},
 'SLIM*SIG2': {'p_inflate': 0.6,
  'max_depth': 22,
  'init_depth': 5,
  'prob_const': 0.15,
  'prob_replace': 0.01,
  'p_prune': 0.5,
  'p_xo': 0.7,
  'p_struct_xo': 0.7},
 'SLIM+ABS': {'p_inflate': 0.1,
  'max_depth': 19,
  'init_depth': 5,
  'prob_const': 0.1,
  'prob_replace': 0.025,
  'p_prune': 0.2,
  'p_xo': 0.5,
  'p_struct_xo': 0.4},
 'SLIM*ABS': {'p_inflate': 0.9,
  'max_depth': 13,
  'init_depth': 5,
  'prob_const': 0.15,
  'prob_replace': 0.02,
  'p_prune': 0.4,
  'p_xo': 0.6,
  'p_struct_xo': 0.3},
 'SLIM+SIG1': {'p_inflate': 0.5,
  'max_depth': 15,
  'init_depth': 7,
  'prob_const': 0.2,
  'prob_replace': 0.025,
  'p_prune': 0.7,
  'p_xo': 0.3,
  'p_struct_xo': 0.4},
 'SLIM*SIG1': {'p_inflate': 0.3,
  'max_depth': 21,
  'init_depth': 10,
  'prob_const': 0.1,
  'prob_replace': 0.01,
  'p_prune': 0.6,
  '

In [175]:
df_stats = pd.DataFrame(columns=["SLIM+SIG2", "SLIM*SIG2", "SLIM+ABS", "SLIM*ABS", "SLIM+SIG1", "SLIM*SIG1"], index=datasets)
for filename in os.listdir('results/SLIM'):
    # For each dataset
    if 'struct' in filename:
        name = filename.split('_struct')[0]
    
    else: 
        continue

    with open('results/SLIM/' + name+'_scaled.pkl', 'rb') as f:
        results = pickle.load(f)
        mean_rmse = np.array([np.mean(values) for keys, values in results['rmse_'].items()])
        std_rmse = np.array([np.std(values) for keys, values in results['rmse_'].items()])
        mean_size = np.array([np.mean(values) for keys, values in results['size'].items()])
        std_size = np.array([np.std(values) for keys, values in results['size'].items()])

    with open('results/SLIM/' + name+'_struct.pkl', 'rb') as f:
        results = pickle.load(f)
        mean_rmse_struct = np.array([np.mean(values) for keys, values in results['rmse_'].items()])
        std_rmse_struct = np.array([np.std(values) for keys, values in results['rmse_'].items()])
        mean_size_struct = np.array([np.mean(values) for keys, values in results['size'].items()])
        std_size_struct = np.array([np.std(values) for keys, values in results['size'].items()])

    print("{:.2f}".format(100*mean_rmse.min()), "{:.2f}".format(100*mean_rmse_struct.min()), "{:.2f}".format(results_corr[name]), "{:.2f}".format(mean_rmse.min()/mean_rmse_struct.min()))
    # print(mean_size.min(), mean_size_struct.min())

13.79 14.83 12.08 0.93
6.37 3.67 0.42 1.74
30.45 30.84 26.66 0.99
12.91 11.72 8.52 1.10
27.64 27.58 15.46 1.00
27.72 28.31 22.98 0.98
12.65 12.85 10.45 0.98
18.01 17.82 16.71 1.01
9.92 9.21 8.94 1.08
9.25 8.79 8.46 1.05
20.73 20.81 18.47 1.00
8.67 8.51 7.18 1.02
25.22 24.79 20.86 1.02
20.82 20.84 20.62 1.00
30.47 30.58 25.92 1.00
7.04 5.40 3.08 1.30


In [165]:
args = {'p_inflate': 0.3,
  'max_depth': 21,
  'init_depth': 10,
  'prob_const': 0.1,
  'prob_replace': 0.01,
  'p_prune': 0.6,
  'p_xo': 0.2,
  'p_struct_xo': 0.7}

results = {}
for dataset in [globals()[i] for i in globals() if 'load' in i][2:]:
  X, y = dataset()
  rm, ma, nrmse, r2, mae, std_rmse, time, train, test, size = test_slim(
              X=X, y=y, args_dict=args, dataset_name='test',
              ms_lower=0, ms_upper=1, n_elites=1,
              iterations=15, scale=True, algorithm='SLIM*SIG1',
              verbose=0, p_train=0.7, show_progress=True,
          )
  rm = np.array(rm)
  rm_min = 100*rm.min()
  results[dataset.__name__] = rm_min
  print(dataset.__name__, rm_min)

  0%|          | 0/15 [00:00<?, ?it/s]

100%|██████████| 15/15 [01:26<00:00,  5.76s/it]


load_resid_build_sale_price 3.077119402587414


100%|██████████| 15/15 [01:39<00:00,  6.61s/it]


load_istanbul 7.180445641279221


100%|██████████| 15/15 [01:43<00:00,  6.92s/it]


load_airfoil 12.081281840801239


100%|██████████| 15/15 [01:41<00:00,  6.77s/it]


load_bike_sharing 0.4183435346931219


100%|██████████| 15/15 [01:22<00:00,  5.52s/it]


load_boston 8.515595644712448


100%|██████████| 15/15 [01:31<00:00,  6.09s/it]


load_breast_cancer 15.458212792873383


100%|██████████| 15/15 [01:32<00:00,  6.19s/it]


load_concrete_slump 22.982238233089447


100%|██████████| 15/15 [01:29<00:00,  5.96s/it]


load_concrete_strength 10.452596098184586


100%|██████████| 15/15 [01:26<00:00,  5.76s/it]


load_diabetes 16.705723106861115


100%|██████████| 15/15 [01:25<00:00,  5.67s/it]


load_efficiency_heating 8.461150527000427


100%|██████████| 15/15 [01:20<00:00,  5.36s/it]


load_efficiency_cooling 8.938560634851456


100%|██████████| 15/15 [01:29<00:00,  5.99s/it]


load_forest_fires 18.470481038093567


100%|██████████| 15/15 [01:45<00:00,  7.03s/it]


load_parkinson_updrs 20.621614158153534


100%|██████████| 15/15 [01:37<00:00,  6.47s/it]


load_ld50 20.862020552158356


100%|██████████| 15/15 [01:37<00:00,  6.48s/it]


load_ppb 25.922706723213196


100%|██████████| 15/15 [01:28<00:00,  5.92s/it]

load_bioav 26.655355095863342


raw.githubusercontent.com/amarmate/SLIM-test/blob/main/testers/test_speed.py

In [146]:
df_stats = pd.DataFrame(columns=["SLIM+SIG2", "SLIM*SIG2", "SLIM+ABS", "SLIM*ABS", "SLIM+SIG1", "SLIM*SIG1"], index=datasets)
for filename in os.listdir('results/SLIM'):
    # For each dataset
    if 'struct' in filename:
        name = filename.split('_struct')[0]
    
    else: 
        continue

    with open('results/SLIM/' + name+'_scaled.pkl', 'rb') as f:
        results_scaled = pickle.load(f)
        test = np.array([np.mean(values) for keys, values in results_scaled['test_fit'].items()])
        train = np.array([np.std(values) for keys, values in results_scaled['train_fit'].items()])
        mean_size = np.array([np.mean(values) for keys, values in results_scaled['size'].items()])
        std_size = np.array([np.std(values) for keys, values in results_scaled['size'].items()])

    with open('results/SLIM/' + name+'_struct.pkl', 'rb') as f:
        results_struct = pickle.load(f)
        test_struct = np.array([np.mean(values) for keys, values in results_struct['test_fit'].items()])
        train_struct = np.array([np.std(values) for keys, values in results_struct['train_fit'].items()])
        mean_size_struct = np.array([np.mean(values) for keys, values in results_struct['size'].items()])
        std_size_struct = np.array([np.std(values) for keys, values in results_struct['size'].items()])

    print('-------------------', name, '-------------------')
    print(test)
    print(test_struct)

------------------- airfoil -------------------
[0.13792237 0.15762735 0.1722157  0.17693558 0.15780798 0.18667119]
[0.14832592 0.16048525 0.15802479 0.16546231 0.15924304 0.19580386]
------------------- bike_sharing -------------------
[0.06761615 0.06552969 0.09000596 0.07510583 0.06371854 0.06733989]
[0.04622429 0.03694668 0.05149901 0.05052477 0.04751019 0.0367056 ]
------------------- bioav -------------------
[0.30995024 0.30741564 0.30952701 0.30450562 0.31006524 0.31943202]
[0.31002265 0.32277876 0.30894084 0.30837021 0.31092197 0.32239372]
------------------- boston -------------------
[0.13493074 0.15354635 0.14400342 0.12906207 0.13281019 0.14386057]
[0.11720274 0.11842243 0.12011071 0.12288083 0.12176637 0.11751374]
------------------- breast_cancer -------------------
[0.27636146 0.32066432 0.31444111 0.3796575  0.30796053 0.37382745]
[0.3083076  0.31549337 0.29649097 0.27580727 0.29800231 0.31951562]
------------------- concrete_slump -------------------
[0.29715798 0.299

### Scaled

In [ ]:
mean_rmsescaled_all = []

for filename in os.listdir('results/SLIM'):
    # For each dataset
    if 'struct' in filename:
        name = filename.split('_struct')[0]
    
    else: 
        continue

    with open('results/SLIM/' + name+'_scaled.pkl', 'rb') as f:
        results = pickle.load(f)
        mean_rmse_scaled = np.array([np.mean(values) for keys, values in results['rmse_'].items()])
        std_rmse_scaled = np.array([np.std(values) for keys, values in results['rmse_'].items()])
        mean_size_scaled = np.array([np.mean(values) for keys, values in results['size'].items()])
        std_size_scaled = np.array([np.std(values) for keys, values in results['size'].items()])

    with open('results/SLIM/' + name+'_unscaled.pkl', 'rb') as f:
        results = pickle.load(f)
        mean_rmse_unscaled = np.array([np.mean(values) for keys, values in results['rmse_'].items()])
        std_rmse_unscaled = np.array([np.std(values) for keys, values in results['rmse_'].items()])
        mean_size_unscaled = np.array([np.mean(values) for keys, values in results['size'].items()])
        std_size_unscaled = np.array([np.std(values) for keys, values in results['size'].items()])

    print(mean_rmse_unscaled - mean_rmse_scaled)

[5.774736  3.339687  6.416489  3.4611561 6.7725782 3.6953611]
[ 0.19473436 -0.135112    0.00161502 -0.15538374  0.21042344 -0.17053461]
[0.5786725  0.3300202  0.58180726 1.1073037  0.5742482  0.13710916]
[ 0.28297538 -0.11620569  0.23852581 -0.0408622   0.3007776  -0.10044187]
[-0.02940136 -0.00075221  0.02381086 -0.10231876 -0.03847641 -0.11358792]
[0.1317721  0.0736379  0.17520446 0.03853512 0.12223953 0.1004498 ]
[0.7285337  0.09196973 0.6079456  0.33276266 0.5302175  0.2063902 ]
[1.2561388  0.27933943 1.204401   0.80767006 1.2289534  0.08553594]
[ 0.37881857 -0.0274969   0.34271827 -0.07985708  0.3543714  -0.09261289]
[ 0.2949314  -0.04556927  0.22712174 -0.06440011  0.23955414 -0.11316216]
[ 0.98276925 -0.09167612  1.1261617  -0.04175651 -0.00819385 -0.14708078]
[-0.0787068   0.00189382 -0.01919091 -0.0042882   0.08407182 -0.188483  ]
[ 0.05149114 -0.05724537 -0.01549685  0.03524458 -0.06683481 -0.00045562]
[0.21347213 0.06166118 0.13586253 0.00580317 0.19740999 0.01181853]
[ 0.29

In [51]:
with open('results/SLIM/airfoil_scaled.pkl', 'rb') as f:
    results = pickle.load(f)
    mean_nrmse_ = [np.mean(values) for keys, values in results['nrmse_'].items()]
    std_nrmse_ = [np.std(values) for keys, values in results['nrmse_'].items()]
    mean_size = [np.mean(values) for keys, values in results['size'].items()]
    std_size = [np.std(values) for keys, values in results['size'].items()]